config/routes.rb
Rails.application.routes.draw do
  resources :bookings_results
  resources :results
  get 'bookings_service_offers/bulk_create'
  root  to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'choose-services', to: 'pages#choose_services'
  resources :service_offers, path: 'services-offered'
  resources :establishments
  resources :cities
  resources :provinces
  resources :bookings do
    member do
      get 'card'
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :bookings_service_offers, path: 'booking-service-offers', only: [:index, :destroy] do
    collection do
      post :bulk_create
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/service_offer.rb
class ServiceOffer < ApplicationRecord
  acts_as_tenant :establishment

  has_rich_text :description
  has_many :bookings_service_offers, dependent: :destroy
  has_many :bookings, through: :bookings_service_offers

  STATUSES = [['Published','published'], ['Draft','draft'], ['Discontinued','discontinued']]

  def self.ransackable_attributes(auth_object = nil)
    ['name', 'description']
  end

  def self.ransackable_associations(auth_object = nil)
    ["bookings", "bookings_service_offers", "establishment"]
  end

end

app/controllers/service_offers_controller.rb
class ServiceOffersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service_offer, only: %i[ show edit update destroy ]

  # GET /service_offers or /service_offers.json
  def index
    # @service_offers = ServiceOffer.all
    @q = ServiceOffer.ransack(params[:q])
    @service_offers = @q.result(distinct: true)
  end

  # GET /service_offers/1 or /service_offers/1.json
  def show
  end

  # GET /service_offers/new
  def new
    @service_offer = ServiceOffer.new
  end

  # GET /service_offers/1/edit
  def edit
  end

  # POST /service_offers or /service_offers.json
  def create
    @service_offer = ServiceOffer.new(service_offer_params)

    respond_to do |format|
      if @service_offer.save
        format.html { redirect_to service_offer_url(@service_offer), notice: "Service offer was successfully created." }
        format.json { render :show, status: :created, location: @service_offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_offers/1 or /service_offers/1.json
  def update
    respond_to do |format|
      if @service_offer.update(service_offer_params)
        format.html { redirect_to service_offer_url(@service_offer), notice: "Service offer was successfully updated." }
        format.json { render :show, status: :ok, location: @service_offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_offers/1 or /service_offers/1.json
  def destroy
    @service_offer.destroy!

    respond_to do |format|
      format.html { redirect_to service_offers_url, notice: "Service offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_offer
      @service_offer = ServiceOffer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_offer_params
      params.require(:service_offer).permit(:establishment_id, :name, :price, :slot, :status, :description)
    end
end

app/helpers/service_offers_helper.rb
module ServiceOffersHelper
end

app/views/service_offers/_form.html.erb
<%= form_with(model: service_offer, class: "contents") do |form| %>
  <% if service_offer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(service_offer.errors.count, "error") %> prohibited this service_offer from being saved:</h2>

      <ul>
        <% service_offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :slot %>
    <%= form.text_field :slot, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/service_offers/_service_offer.html.erb
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600" id="<%= dom_id service_offer %>">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <%= service_offer.name %>
                </th>
                <td class="px-6 py-4">
                    <%= formatted_price( service_offer.price) %>
                </td>
                <td class="px-6 py-4">
                    <%= service_offer.limited_per_day ? 'Yes' : 'No'%>
                </td>
                <td class="px-6 py-4">
                    <%= service_offer.slot.nil? ? 'Unlimited/Until closing' : service_offer.slot %>
                </td>
                <td class="px-6 py-4">
                    <%= service_offer.bookings.bookings_this_month.count %>
                </td>
                <td class="px-6 py-4">
                    <%= service_offer.bookings.count %>
                </td>
                <td class="px-6 py-4">
                    <%= service_offer.status %>
                </td>
                <td class="px-6 py-4 text-right">
                  <%= link_to "Edit", edit_service_offer_path(service_offer), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
            </tr>


<!-- <div >
  <p class="my-5">
    <strong class="block font-medium mb-1">Establishment:</strong>
    <%#= service_offer.establishment_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slot:</strong>
    <%#= service_offer.slot %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%#= service_offer.description %>
  </p>

  <%# if action_name != "show" %>
    <%#= link_to "Show this service offer", service_offer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <%# end %>
</div>
-->

app/views/service_offers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing service offer</h1>

  <%= render "form", service_offer: @service_offer %>

  <%= link_to "Show this service offer", @service_offer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to service offers", service_offers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/service_offers/index.html.erb
<div class="mx-3 mt-5">
<h1 class="text-2xl font-bold text-white my-3">Services</h1>
<div class="grid justify-items-end py-3">
  <div class="relative">
    <div class="absolute inset-y-0 left-0 rtl:inset-r-0 rtl:right-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
            </div>
            <%= search_form_for @q, class: 'flex gap-2' do |f| %>
            <%= f.search_field :name_or_description_cont, placeholder: 'Search', class: 'block p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>

            <%= f.submit 'Search', class: 'px-5 py-3 text-base font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
          <% end %>
  </div>
</div>
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Price
                </th>
                <th scope="col" class="px-6 py-3">
                    Is limited per day?
                </th>
                <th scope="col" class="px-6 py-3">
                    Slots
                </th>
                <th scope="col" class="px-6 py-3">
                    Monthly booking
                </th>
                <th scope="col" class="px-6 py-3">
                    Total bookings
                </th>
                <th scope="col" class="px-6 py-3">
                    Status
                </th>
                <th scope="col" class="px-6 py-3">
                    <span class="sr-only">Edit</span>
                </th>
            </tr>
        </thead>
        <tbody>
            <%= render @service_offers %>
          </tbody>
    </table>
</div>
</div>

app/views/service_offers/index_old.html.erb
<div class="w-full">
 <%= render partial: 'shared/notifications', locals: { message: flash[:notice], message_type: 'notice'} if notice.present? %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Service offers</h1>
    <%= link_to "New service offer", new_service_offer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="service_offers" class="min-w-full">
    <%= render @service_offers %>
  </div>
</div>

app/views/service_offers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New service offer</h1>

  <%= render "form", service_offer: @service_offer %>

  <%= link_to "Back to service offers", service_offers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/service_offers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @service_offer %>

    <%= link_to "Edit this service_offer", edit_service_offer_path(@service_offer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this service_offer", service_offer_path(@service_offer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to service_offers", service_offers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>