config/routes.rb
Rails.application.routes.draw do
  resources :bookings_results
  resources :results
  get 'bookings_service_offers/bulk_create'
  root  to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'choose-services', to: 'pages#choose_services'
  resources :service_offers, path: 'services-offered'
  resources :establishments
  resources :cities
  resources :provinces
  resources :bookings do
    member do
      get 'card'
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :bookings_service_offers, path: 'booking-service-offers', only: [:index, :destroy] do
    collection do
      post :bulk_create
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/establishment.rb
class Establishment < ApplicationRecord
  belongs_to :city

  has_many :establishments_users, dependent: :destroy
  has_many :users, through: :establishments_users
  has_many :service_offers, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :set_establishment, only: %i[ show edit update destroy ]

  # GET /establishments or /establishments.json
  def index
    @establishments = Establishment.all
  end

  # GET /establishments/1 or /establishments/1.json
  def show
  end

  # GET /establishments/new
  def new
    @establishment = Establishment.new
  end

  # GET /establishments/1/edit
  def edit
  end

  # POST /establishments or /establishments.json
  def create
    @establishment = Establishment.new(establishment_params)

    respond_to do |format|
      if @establishment.save
        format.html { redirect_to establishment_url(@establishment), notice: "Establishment was successfully created." }
        format.json { render :show, status: :created, location: @establishment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establishments/1 or /establishments/1.json
  def update
    respond_to do |format|
      if @establishment.update(establishment_params)
        format.html { redirect_to establishment_url(@establishment), notice: "Establishment was successfully updated." }
        format.json { render :show, status: :ok, location: @establishment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establishments/1 or /establishments/1.json
  def destroy
    @establishment.destroy!

    respond_to do |format|
      format.html { redirect_to establishments_url, notice: "Establishment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establishment
      @establishment = Establishment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def establishment_params
      params.require(:establishment).permit(:name, :address, :phone_number, :subdomain, :domain, :status, :booking_offset, :city_id)
    end
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/_establishment.html.erb
<div id="<%= dom_id establishment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= establishment.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= establishment.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone number:</strong>
    <%= establishment.phone_number %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Subdomain:</strong>
    <%= establishment.subdomain %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Domain:</strong>
    <%= establishment.domain %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= establishment.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Booking offset:</strong>
    <%= establishment.booking_offset %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= establishment.city_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this establishment", establishment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this establishment", edit_establishment_path(establishment), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/establishments/_form.html.erb
<%= form_with(model: establishment, class: "contents") do |form| %>
  <% if establishment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(establishment.errors.count, "error") %> prohibited this establishment from being saved:</h2>

      <ul>
        <% establishment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :subdomain %>
    <%= form.text_field :subdomain, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :domain %>
    <%= form.text_field :domain, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :booking_offset %>
    <%= form.number_field :booking_offset, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city_id %>
    <%= form.text_field :city_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/establishments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing establishment</h1>

  <%= render "form", establishment: @establishment %>

  <%= link_to "Show this establishment", @establishment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to establishments", establishments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/establishments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Establishments</h1>
    <%= link_to "New establishment", new_establishment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="establishments" class="min-w-full">
    <%= render @establishments %>
  </div>
</div>

app/views/establishments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New establishment</h1>

  <%= render "form", establishment: @establishment %>

  <%= link_to "Back to establishments", establishments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/establishments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @establishment %>

    <%= link_to "Edit this establishment", edit_establishment_path(@establishment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this establishment", establishment_path(@establishment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to establishments", establishments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>